#ifndef GAME_EVENT_TYPE_H
#define GAME_EVENT_TYPE_H

enum class GameEventType
{
    PLAYER_MOVED,
    PLAYER_ATTACKED,
    PLAYER_DAMAGED,
    PLAYER_MODE_CHANGED,
    SPELL_CAST,
    SPELL_RECEIVED,
    ENEMY_MOVED,
    ENEMY_DAMAGED,
    BUILDING_DAMAGED,
    BUILDING_SPAWNED_ENEMY,
    LEVEL_CHANGED
};

#endif