#ifndef CONSTANTS_H
#define CONSTANTS_H


#define PLAYER_DEFAULT_HP 10000
#define PLAYER_DEFAULT_BASE_DMG 1000


#define RANGE_ATTACK_MAX_DISTANCE 3
#define MELEE_ATTACK_MAX_DISTANCE 1
#define DIRECT_SPELL_RANGE 3
#define AOE_SPELL_RANGE 3
#define TOWER_ATTACK_RANGE 4


#define RANGE_ATTACK_BONUS 3
#define MELEE_ATTACK_BONUS 5
#define DIRECT_SPELL_DAMAGE 20
#define DIRECT_SPELL_WEAK_DAMAGE 10
#define AOE_SPELL_DAMAGE 12
#define TRAP_DAMAGE 15


#define SCORE_PER_ENEMY 10
#define SCORE_MILESTONE_FOR_SPELL 50


#define MIN_FIELD_SIZE 10
#define MAX_FIELD_SIZE 25
#define INIT_WALL_PROBABILITY 45
#define SMOOTH_WALL_NEIGHBOR_HIGH 5
#define SMOOTH_WALL_NEIGHBOR_LOW 3
#define SLOWING_CELLS_DIVISOR 10
#define ENEMY_DENSITY_DIVISOR 30
#define ENEMY_MIN_COUNT 2
#define BUILDING_DENSITY_DIVISOR 100
#define BUILDING_MIN_COUNT 1


#define ENEMY0_HP 25
#define ENEMY0_DMG 6
#define ENEMY1_HP 40
#define ENEMY1_DMG 10
#define ENEMY2_HP 60
#define ENEMY2_DMG 15


#define BUILD0_HP 80
#define BUILD1_HP 110
#define BUILD2_HP 140
#define BUILD0_ENEMY_HP 20
#define BUILD0_ENEMY_DMG 5
#define BUILD1_ENEMY_HP 35
#define BUILD1_ENEMY_DMG 8
#define BUILD2_ENEMY_HP 50
#define BUILD2_ENEMY_DMG 12
#define BUILD_COOLDOWN_MIN 3
#define BUILD_COOLDOWN_MAX 8


#define TOWER_HP 90
#define TOWER_COOLDOWN 1


#define PLAYER_HAND_CAPACITY 3


#define LEVEL_COMPLETE_ENEMY_THRESHOLD 0
#define LEVEL_COMPLETE_BUILDING_THRESHOLD 0
#define LEVEL_COMPLETE_TOWER_THRESHOLD 0
#define BASE_FIELD_SIZE 15
#define LEVEL_SIZE_INCREMENT 2
#define LEVEL_ENEMY_HP_BONUS 5
#define LEVEL_ENEMY_DMG_BONUS 2
#define LEVEL_ENEMY_COUNT_MULTIPLIER 1.2


#define UPGRADE_HP_COST 100
#define UPGRADE_DMG_COST 100
#define UPGRADE_HAND_COST 150


#define PLAYER_SYMBOL '@'
#define ENEMY_SYMBOL 'E'
#define BUILDING_SYMBOL 'B'
#define TOWER_SYMBOL 'T'
#define TRAP_SYMBOL 'X'
#define EMPTY_SYMBOL '.'

#endif 
