all:
	g++ main.cpp game.cpp game_field.cpp game_cell.cpp player.cpp enemy.cpp spell.cpp enemy_tower.cpp hand.cpp lightning_spell.cpp fireball_spell.cpp trap_spell.cpp entity.cpp game_save.cpp -o main && ./main
