#ifndef CONSTANTS_H
#define CONSTANTS_H

#define DEFAULT_PLAYER_HEALTH 1000
#define DEFAULT_PLAYER_MELEE_DAMAGE 15
#define DEFAULT_PLAYER_RANGED_DAMAGE 10
#define PLAYER_HEALTH_PER_LEVEL 20
#define PLAYER_MELEE_DAMAGE_PER_LEVEL 5
#define PLAYER_RANGED_DAMAGE_PER_LEVEL 3

#define DEFAULT_ENEMY_HEALTH 50
#define DEFAULT_ENEMY_DAMAGE 15
#define GOBLIN_HEALTH 40
#define GOBLIN_DAMAGE 10
#define ORC_HEALTH 80
#define ORC_DAMAGE 20
#define TROLL_HEALTH 120
#define TROLL_DAMAGE 25

//поле
#define MIN_FIELD_SIZE 10
#define MAX_FIELD_SIZE 25
#define DEFAULT_FIELD_SIZE 15
#define DEFAULT_SPAWN_INTERVAL 5

#define MELEE_ATTACK_RANGE 1.5
#define RANGED_ATTACK_RANGE 3.5
#define HEAL_AMOUNT 30

#define SCORE_PER_KILL 10
#define SCORE_PER_DESTROY 25

//здание
#define BUILDING_DEFAULT_HEALTH 100
#define SPAWN_INTERVAL 5


#define EASY_HEALTH 150
#define EASY_DAMAGE_BONUS 5
#define NORMAL_HEALTH 100
#define HARD_HEALTH 75
#define HARD_DAMAGE_PENALTY -3

#define MAX_SPELL_HAND_SIZE 5


// Система заклинаний
#define SPELL_DIRECT_DAMAGE_COST 10
#define SPELL_DIRECT_DAMAGE_RANGE 3
#define SPELL_DIRECT_DAMAGE_DAMAGE 25

#define SPELL_AREA_DAMAGE_COST 15
#define SPELL_AREA_DAMAGE_RANGE 2  
#define SPELL_AREA_DAMAGE_DAMAGE 20
#define SPELL_AREA_SIZE 2


#define SPELL_TRAP_COST 8
#define SPELL_TRAP_RANGE 2
#define SPELL_TRAP_DAMAGE 15

#define SPELL_SUMMON_COST 20
#define SPELL_SUMMON_RANGE 1

#define SPELL_BUFF_COST 12
#define SPELL_BUFF_RANGE 0

// Мана игрока
#define PLAYER_START_MANA 50
#define PLAYER_MAX_MANA 50
#define MANA_RESTORE_PER_TURN 5

// Размер руки
#define SPELL_HAND_SIZE 5


// Ловушки
#define SPELL_TRAP_COST 8
#define SPELL_TRAP_RANGE 2
#define SPELL_TRAP_DAMAGE 15

// Вражеские башни  
#define ENEMY_TOWER_HEALTH 80
#define ENEMY_TOWER_ATTACK_RANGE 4
#define ENEMY_TOWER_DAMAGE 12
#define ENEMY_TOWER_ATTACK_COOLDOWN 2

//союзники
#define ALLY_DEFAULT_HEALTH 50
#define ALLY_DEFAULT_DAMAGE 10
#define ALLY_MOVE_RANGE 1
#define ALLY_ATTACK_RANGE 1.5
#define SPELL_SUMMON_COST 20
#define SPELL_SUMMON_RANGE 1

//улучшения
#define SPELL_BUFF_COST 12
#define SPELL_BUFF_RANGE 0

#endif