#ifndef DEFINES_H
#define DEFINES_H

#define BOARD_WIDTH 20
#define BOARD_HEIGHT 15
#define WALL_CHANCE 0.15
#define SLOW_CHANCE 0.05

#define PLAYER_START_HEALTH 100
#define MELEE_DAMAGE 20
#define RANGED_DAMAGE 15
#define MELEE_RANGE 1.5
#define RANGED_RANGE 5.0

#define PLAYER_HAND_SIZE 5
#define KILLS_FOR_NEW_SPELL 3

#define ENEMY_DEFAULT_HEALTH 40
#define ENEMY_DEFAULT_DAMAGE 10

#define ENEMY_BUILDING_HEALTH 150
#define ENEMY_BUILDING_SPAWN_RATE 6

#define ENEMY_TOWER_HEALTH 100
#define ENEMY_TOWER_DAMAGE 12
#define ENEMY_TOWER_RANGE 5.0
#define ENEMY_TOWER_COOLDOWN 2

#define ALLY_HEALTH 50
#define ALLY_DAMAGE 15

#define SCORE_PER_KILL 50
#define SCORE_PER_BUILDING_DESTROYED 85
#define SCORE_PER_TOWER_DESTROYED 125

#define DIRECT_DAMAGE_SPELL_DAMAGE 35
#define DIRECT_DAMAGE_SPELL_RANGE 6.0
#define DIRECT_DAMAGE_SPELL_RANGE_BONUS 2.0 

#define AOE_SPELL_DAMAGE 25
#define AOE_SPELL_RANGE 5.0
#define AOE_SPELL_AREA_SIZE 2
#define AOE_SPELL_AREA_SIZE_BONUS 1

#define TRAP_SPELL_RANGE 3.0
#define TRAP_DAMAGE 40
#define TRAP_DAMAGE_BONUS 20

#define SUMMON_SPELL_RANGE 2.0
#define SUMMON_SPELL_ALLY_COUNT 1
#define SUMMON_SPELL_ALLY_COUNT_BONUS 1
#define ENHANCEMENT_SPELL_COST 100

#define SPELL_ID_DIRECT_DAMAGE 0
#define SPELL_ID_AOE 1
#define SPELL_ID_TRAP 2
#define SPELL_ID_SUMMON 3
#define SPELL_ID_ENHANCE 4

#endif